name: dodge_game
description: flutter dodge game

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  flame: ^1.8.1
  sensors_plus: ^3.0.2
  logger: ^1.4.0
  get: ^4.6.5
  very_good_analysis: ^5.0.0+1
  hive: ^2.2.3
  intl: ^0.18.1
  json_annotation:
  path_provider:
  shared_preferences: ^2.2.0

  # firebase
  firebase_core: ^2.14.0
  firebase_core_web: ^2.6.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  flutter_signin_button: ^2.0.0

  # google sign in
  google_sign_in: ^6.1.4

  # kakao login
  kakao_flutter_sdk_user: ^1.4.3

  # fonts
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: any
  build_runner: any
  json_serializable:

flutter:

  uses-material-design: true

  assets:
    - assets/images/

