name: dodge_game
description: flutter dodge game

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flame: 1.2.0
  sensors_plus: ^1.3.2
  logger: ^1.1.0
  get: ^4.6.5
  very_good_analysis: ^3.0.1
  sqflite: ^2.0.3+1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Black.ttf
        - asset: assets/fonts/Merriweather/Merriweather-BlackItalic.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather/Merriweather-BoldItalic.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Italic.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Light.ttf
        - asset: assets/fonts/Merriweather/Merriweather-LightItalic.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
