name: Just Flutter Build
on:
  push:
    branches:
      - master

jobs:
  # internal test
  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo '${{ secrets.TEST_TXT }}' > ./lib/firebase_options.dart
      - run: cat ./lib/firebase_options.dart