name: Just Flutter Build
on:
  push:
    branches:
      - master

jobs:
  # internal test
  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.3.9'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      - name: Install packages
        run: flutter pub get
      - run: echo '${{ secrets.FIREBASE_OPTIONS }}' > ./lib/firebase_options.dart
      - run: echo '${{ secrets.GOOGLE_SERVICES }}' > ./android/app/google-services.json
      - run: echo '${{ secrets.KAKAO_SDK_APPKEY }}' > ./android/local.properties
      - name: Prebuild
        run: flutter build appbundle
